version: '3'

services:
  api:
    image: elektron-canteen-backend:latest
    restart: always
    environment:
      MONGO_URL: mongodb://mongo:27017/canteen
      JWT_SECRET_KEY: CHANGE_ME
    ports:
#      your port is on left
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db