name: Push image to ghcr.io

on:
  push:


jobs:
  push:
    name: "elektron-canteen-backend"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: piotrek-hub
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Get short SHA for tag
        uses: 2428392/gh-truncate-string-action@v1.1.0
        id: truncatedString
        with:
          stringToTruncate: ${{ github.sha }}
          maxLength: 7
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/elektron-canteen-backend:latest
            ghcr.io/${{ github.repository_owner }}/elektron-canteen-backend:${{ steps.truncatedString.outputs.string }}
